# Generated by Django 4.2.23 on 2025-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteadvertisement',
            options={'verbose_name': 'Избранное объявление', 'verbose_name_plural': 'Избранные объявления'},
        ),
        migrations.AddConstraint(
            model_name='favoriteadvertisement',
            constraint=models.UniqueConstraint(fields=('advert', 'user'), name='unique_together_advert_user_constraint'),
        ),
    ]
